import { initialConfig } from "./logo-constants";
import type { LogoConfig } from "./logo-types";

export const presets: { name: string; config: Partial<LogoConfig> }[] = [
  {
    name: "Default",
    config: initialConfig,
  },
  {
    name: "Modern",
    config: {
      ...initialConfig,
      iconType: "lucide",
      iconName: "Zap",
      bgMode: "gradient",
      gradientStart: "#10b981",
      gradientEnd: "#06b6d4",
      gradientAngle: [45],
      radius: [64],
      strokeWidth: [2.5],
    },
  },
  {
    name: "Minimal",
    config: {
      ...initialConfig,
      iconType: "lucide",
      iconName: "Box",
      bgMode: "solid",
      bgColor: "#18181b",
      radius: [0],
      strokeWidth: [1.5],
    },
  },
  {
    name: "Bat",
    config: {
      ...initialConfig,
      iconType: "flaticon",
      iconName: "bat",
      bgMode: "solid",
      bgColor: "#000000",
      iconColor: "#fbbf24",
      radius: [140],
      borderWidth: [4],
      borderColor: "#fbbf24",
    },
  },
  {
    name: "Cyber",
    config: {
      ...initialConfig,
      iconType: "lucide",
      iconName: "Cpu",
      bgMode: "solid",
      bgColor: "#09090b",
      iconColorMode: "gradient",
      iconColorGradientStart: "#06b6d4",
      iconColorGradientEnd: "#d946ef",
      iconColorGradientAngle: [45],
      radius: [32],
      strokeWidth: [2],
      shadowColor: "#06b6d4",
      shadowOpacity: [0.4],
      shadowBlur: [40],
    },
  },
  {
    name: "Retro",
    config: {
      ...initialConfig,
      iconType: "lucide",
      iconName: "Radio",
      bgMode: "gradient",
      gradientStart: "#f59e0b",
      gradientEnd: "#d97706",
      gradientAngle: [135],
      iconColor: "#fffbeb",
      radius: [40],
      borderWidth: [4],
      borderColor: "#78350f",
      shadowColor: "#d97706",
    },
  },
  {
    name: "Nature",
    config: {
      ...initialConfig,
      iconType: "lucide",
      iconName: "Leaf",
      bgMode: "gradient",
      gradientStart: "#4ade80",
      gradientEnd: "#16a34a",
      gradientAngle: [180],
      iconColor: "#ffffff",
      radius: [100],
      strokeWidth: [2],
      shadowColor: "#166534",
      shadowOpacity: [0.3],
    },
  },
  {
    name: "Tech",
    config: {
      ...initialConfig,
      iconType: "lucide",
      iconName: "Database",
      bgMode: "solid",
      bgColor: "#0f172a",
      iconColor: "#38bdf8",
      radius: [16],
      strokeWidth: [2],
      borderWidth: [2],
      borderColor: "#1e293b",
      shadowColor: "#38bdf8",
      shadowOpacity: [0.2],
    },
  },
  {
    name: "Bubble",
    config: {
      ...initialConfig,
      iconType: "lucide",
      iconName: "Cloud",
      bgMode: "gradient",
      gradientStart: "#f472b6",
      gradientEnd: "#a855f7",
      gradientAngle: [45],
      iconColor: "#ffffff",
      radius: [80],
      strokeWidth: [2.5],
      shadowColor: "#a855f7",
      shadowBlur: [30],
      shadowOpacity: [0.4],
    },
  },
  {
    name: "Sharp",
    config: {
      ...initialConfig,
      iconType: "lucide",
      iconName: "Triangle",
      bgMode: "solid",
      bgColor: "#000000",
      iconColor: "#ffffff",
      radius: [0],
      strokeWidth: [3],
      shadowEnabled: false,
    },
  },
  {
    name: "Glass",
    config: {
      ...initialConfig,
      iconType: "lucide",
      iconName: "Droplets",
      bgMode: "gradient",
      gradientStart: "#e0f2fe",
      gradientEnd: "#bae6fd",
      gradientAngle: [135],
      iconColor: "#0284c7",
      radius: [48],
      strokeWidth: [1.5],
      shadowColor: "#0ea5e9",
      shadowBlur: [20],
      shadowOpacity: [0.2],
      borderWidth: [1],
      borderColor: "#ffffff",
    },
  },
  {
    name: "Sunset",
    config: {
      ...initialConfig,
      iconType: "lucide",
      iconName: "Sun",
      bgMode: "gradient",
      gradientStart: "#f97316",
      gradientEnd: "#9333ea",
      gradientAngle: [160],
      iconColor: "#ffffff",
      radius: [100],
      strokeWidth: [2],
      shadowColor: "#9333ea",
      shadowOpacity: [0.3],
    },
  },
  {
    name: "Gamer",
    config: {
      ...initialConfig,
      iconType: "lucide",
      iconName: "Gamepad2",
      bgMode: "solid",
      bgColor: "#171717",
      iconColor: "#ef4444",
      radius: [24],
      strokeWidth: [2],
      borderWidth: [2],
      borderColor: "#ef4444",
      shadowColor: "#ef4444",
      shadowOpacity: [0.5],
      shadowBlur: [20],
    },
  },
  {
    name: "Zen",
    config: {
      ...initialConfig,
      iconType: "lucide",
      iconName: "Circle",
      bgMode: "solid",
      bgColor: "#f5f5f4",
      iconColor: "#57534e",
      radius: [100],
      strokeWidth: [1],
      shadowEnabled: false,
      borderWidth: [1],
      borderColor: "#d6d3d1",
    },
  },
  {
    name: "Neon",
    config: {
      ...initialConfig,
      iconType: "lucide",
      iconName: "Activity",
      bgMode: "solid",
      bgColor: "#000000",
      iconColor: "#22c55e",
      radius: [12],
      strokeWidth: [2],
      borderWidth: [2],
      borderColor: "#d946ef",
      shadowColor: "#22c55e",
      shadowBlur: [20],
      shadowOpacity: [0.5],
    },
  },
  {
    name: "Coffee",
    config: {
      ...initialConfig,
      iconType: "lucide",
      iconName: "Coffee",
      bgMode: "gradient",
      gradientStart: "#78350f",
      gradientEnd: "#451a03",
      gradientAngle: [180],
      iconColor: "#fef3c7",
      radius: [40],
      strokeWidth: [2],
      shadowColor: "#451a03",
    },
  },
  {
    name: "Space",
    config: {
      ...initialConfig,
      iconType: "lucide",
      iconName: "Rocket",
      bgMode: "gradient",
      gradientStart: "#0f172a",
      gradientEnd: "#312e81",
      gradientAngle: [135],
      iconColorMode: "gradient",
      iconColorGradientStart: "#e2e8f0",
      iconColorGradientEnd: "#94a3b8",
      radius: [32],
      strokeWidth: [1.5],
      shadowColor: "#312e81",
      shadowBlur: [30],
    },
  },
  {
    name: "Love",
    config: {
      ...initialConfig,
      iconType: "lucide",
      iconName: "Heart",
      bgMode: "gradient",
      gradientStart: "#fce7f3",
      gradientEnd: "#fbcfe8",
      gradientAngle: [45],
      iconColor: "#db2777",
      iconFillColor: "#db2777",
      iconFillOpacity: [20],
      radius: [100],
      strokeWidth: [2],
      shadowColor: "#db2777",
      shadowOpacity: [0.2],
    },
  },
  {
    name: "Music",
    config: {
      ...initialConfig,
      iconType: "lucide",
      iconName: "Music",
      bgMode: "solid",
      bgColor: "#18181b",
      iconColorMode: "gradient",
      iconColorGradientStart: "#c084fc",
      iconColorGradientEnd: "#22d3ee",
      gradientAngle: [90],
      radius: [24],
      strokeWidth: [2],
      shadowEnabled: false,
    },
  },
  {
    name: "Secure",
    config: {
      ...initialConfig,
      iconType: "lucide",
      iconName: "ShieldCheck",
      bgMode: "solid",
      bgColor: "#eff6ff",
      iconColor: "#2563eb",
      radius: [16],
      strokeWidth: [2],
      borderWidth: [2],
      borderColor: "#bfdbfe",
      shadowColor: "#2563eb",
      shadowOpacity: [0.1],
    },
  },
  {
    name: "Idea",
    config: {
      ...initialConfig,
      iconType: "lucide",
      iconName: "Lightbulb",
      bgMode: "solid",
      bgColor: "#fefce8",
      iconColor: "#ca8a04",
      radius: [32],
      strokeWidth: [2],
      shadowColor: "#ca8a04",
      shadowBlur: [40],
      shadowOpacity: [0.3],
    },
  },
  {
    name: "Storm",
    config: {
      ...initialConfig,
      iconType: "lucide",
      iconName: "CloudLightning",
      bgMode: "gradient",
      gradientStart: "#4b5563",
      gradientEnd: "#1f2937",
      gradientAngle: [180],
      iconColor: "#fbbf24",
      radius: [20],
      strokeWidth: [2],
      shadowColor: "#000000",
      shadowOpacity: [0.4],
    },
  },
  {
    name: "Target",
    config: {
      ...initialConfig,
      iconType: "lucide",
      iconName: "Target",
      bgMode: "solid",
      bgColor: "#ffffff",
      iconColor: "#dc2626",
      radius: [100],
      strokeWidth: [2],
      borderWidth: [4],
      borderColor: "#fee2e2",
      shadowEnabled: false,
    },
  },
  {
    name: "Ghost",
    config: {
      ...initialConfig,
      iconType: "lucide",
      iconName: "Ghost",
      bgMode: "solid",
      bgColor: "#000000",
      iconColor: "#ffffff",
      iconOpacity: [90],
      radius: [48],
      strokeWidth: [1.5],
      shadowColor: "#ffffff",
      shadowBlur: [30],
      shadowOpacity: [0.2],
    },
  },
  {
    name: "Studio",
    config: {
      ...initialConfig,
      iconType: "lucide",
      iconName: "Palette",
      bgMode: "solid",
      bgColor: "#ffffff",
      iconColor: "#000000",
      iconPosition: { x: 0, y: -40 },
      texts: [
        {
          id: "studio-text",
          text: "Studio",
          x: 0,
          y: 60,
          fontSize: 56,
          color: "#000000",
          fontWeight: "400",
          fontFamily: "Playfair Display",
        },
      ],
      radius: [0],
      borderWidth: [2],
      borderColor: "#000000",
      shadowEnabled: false,
    },
  },
  {
    name: "Dev",
    config: {
      ...initialConfig,
      iconType: "lucide",
      iconName: "Terminal",
      bgMode: "gradient",
      gradientStart: "#1e1e1e",
      gradientEnd: "#000000",
      gradientAngle: [45],
      iconColor: "#4ade80",
      iconPosition: { x: -70, y: 0 },
      texts: [],
      radius: [12],
      shadowColor: "#4ade80",
      shadowOpacity: [0.2],
    },
  },
  {
    name: "Social",
    config: {
      ...initialConfig,
      iconType: "lucide",
      iconName: "MessageCircle",
      bgMode: "gradient",
      gradientStart: "#8b5cf6",
      gradientEnd: "#ec4899",
      gradientAngle: [135],
      iconColor: "#ffffff",
      iconPosition: { x: 0, y: -35 },
      texts: [
        {
          id: "social-text",
          text: "Connect",
          x: 0,
          y: 65,
          fontSize: 44,
          color: "#ffffff",
          fontWeight: "800",
          fontFamily: "Lato",
        },
      ],
      radius: [40],
      shadowColor: "#ec4899",
    },
  },
  {
    name: "Heavy",
    config: {
      ...initialConfig,
      iconType: "lucide",
      iconName: "Dumbbell",
      bgMode: "solid",
      bgColor: "#171717",
      iconColor: "#dc2626",
      iconPosition: { x: 0, y: -40 },
      texts: [
        {
          id: "gym-text",
          text: "GYM",
          x: 0,
          y: 75,
          fontSize: 80,
          color: "#ffffff",
          fontWeight: "900",
          fontFamily: "Oswald",
        },
      ],
      radius: [0],
      strokeWidth: [2.5],
      shadowEnabled: false,
      iconSize: [50],
    },
  },
  {
    name: "Blacksmith",
    config: {
      ...initialConfig,
      iconType: "lucide",
      iconName: "Hammer",
      bgMode: "solid",
      bgColor: "#27272a",
      iconColor: "#fb923c",
      radius: [12],
      borderWidth: [2],
      borderColor: "#fb923c",
      texts: [
        {
          id: "blacksmith-text",
          text: "FORGE",
          x: 0,
          y: 70,
          fontSize: 60,
          color: "#fb923c",
          fontWeight: "400",
          fontFamily: "Anton",
        },
      ],
      iconPosition: { x: 0, y: -40 },
    },
  },
];
